#spring:
#  datasource:
#   url: jdbc:h2:./devdb
#   username: sa
# jpa:
#   hibernate:
#     ddl-auto: create-drop
#veritabanına yazma sırasında validation yapma
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver